# Experiment with Markov Chains

## Set up functions 

In [1]:
import numpy as np
from numpy.testing import assert_array_equal
from numpy.linalg import matrix_power, eig
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Some utils to verify the correctness of the array and matrix
def assert_initial_state(init_state):
    assert(isinstance(init_state, np.ndarray)), "`init_state` should be in numpy.ndarray type"
    assert(np.sum(init_state) == 1), "Sum of the vector `init_state` should be 1 but {} here.".format(np.sum(init_state))

def assert_transition_matrix(transition_matrix):
    assert(isinstance(transition_matrix, np.ndarray)), "`transition_matrix` should be in numpy.ndarray type"
    assert(len(transition_matrix.shape) == 2), "`transition_matrix` is only 2-D for this experiment"
    assert(transition_matrix.shape[0] == transition_matrix.shape[1]), "`transition_matrix` should be a squared matrix"
    assert_array_equal(x=np.sum(transition_matrix, 1), 
                       y=np.ones(transition_matrix.shape[0]),
                       err_msg="Rows in `transition_matrix` should sum up to 1",
                       verbose=True)

def get_state(init, transition, timestep):
    assert_initial_state(init)
    assert_transition_matrix(transition)
    assert(isinstance(timestep, int)), "Timestep must be an integer"
    return np.matmul(init, matrix_power(transition, timestep))

## Set initial states and check the evolution of the state probabilities

In [2]:
init_state = np.array([0, 1])
# Transition probability
prob_01 = 0.2
prob_10 = 0.6

# Stationary probability
prob_00 = 1 - prob_01
prob_11 = 1 - prob_10
transition_matrix = np.array([[prob_00, prob_01], 
                              [prob_10, prob_11]])
print("transition_matrix\n", transition_matrix)

states = []
for timestep in range(10):
    state = get_state(init_state, transition_matrix, timestep)
    states.append(state)
    
states_df = pd.DataFrame(states, columns=["state 0", "state 1"]) 
states_df

transition_matrix
 [[ 0.8  0.2]
 [ 0.6  0.4]]


state 0   state 1
0  0.000000  1.000000
1  0.600000  0.400000
2  0.720000  0.280000
3  0.744000  0.256000
4  0.748800  0.251200
5  0.749760  0.250240
6  0.749952  0.250048
7  0.749990  0.250010
8  0.749998  0.250002
9  0.750000  0.250000

## Verify the convergence solution

In [3]:
PT = np.transpose(transition_matrix)
stationary = np.array([0.750000, 0.250000])
np.matmul(PT, np.transpose(stationary))

array([ 0.75,  0.25])

In [4]:
first_eig_vector = eig(PT)[1][:,0]
normalised_eig = first_eig_vector/sum(first_eig_vector)  # Normalise to sum = 1
normalised_eig

array([ 0.75,  0.25])